INSERT INTO USER (USERNAME, PASSWORD) VALUES ('fpmoles', 'password');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('jdoe', 'password');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('fpmoles', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('fpmoles', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('jdoe', 'USER');